from time import sleep

print("--------------------INICIANDO SUB-PROCESSO DE CONSTRUCAO--------------------")
sleep(1)
print("Iniciando codificação...")
sleep(0.7)
print("Criando modulos necessarios...")
sleep(0.7)
print("Criando funcoes para cada modulo...")
sleep(0.7)
print("Escrevendo arquivo principal...")
sleep(0.7)
print("Criando variaveis e estruturas...")
sleep(0.7)
print("Chamando funcoes...")
sleep(0.7)
print("Adicionando comentarios ao codigo...")
sleep(0.7)
print("Implementando interface grafica ao software...")
sleep(0.7)
print("--------------------FIM DO SUB-PROCESSO DE CONSTRUCAO--------------------\n")
sleep(1.5)