from time import sleep

print("--------------------INICIANDO SUB-PROCESSO DE PROJETO--------------------")
sleep(1)
print("Buscando relacoes entre requisitos...")
sleep(0.7)
print("Associando requisitos funcionais aos nao funcionais...")
sleep(0.7)
print("Associando requisitos as regras de negocio...")
sleep(0.7)
print("Separando requisitos que podem ser representados por um mesmo modulo...")
sleep(0.7)
print("Gerando UML...")
sleep(0.7)
print("Criando cronograma do projeto...")
sleep(0.7)
print("--------------------FIM DO SUB-PROCESSO DE PROJETO--------------------\n")
sleep(1.5)