from time import sleep

print("--------------------INICIANDO SUB-PROCESSO DE REQUISITOS--------------------")
sleep(1.0)
print("Iniciando análise do problema...")
sleep(0.7)
print("Reconhecendo o contexto do produto...")
sleep(0.7)
print("Avaliando viabilidade do projeto...")
sleep(0.7)
print("...")
sleep(0.7)

print("Iniciando análise de requisitos..")
sleep(0.7)
print("Identificando tipos de requisitos...")
sleep(0.7)
print("Definindo o domínio...")
sleep(0.7)
print("...os dados...")
sleep(0.7)
print("...os requisitos funcionais e os não funcionais...")
sleep(0.7)
print("Definindo requisitos de usuário...")
sleep(0.7)
print("Identificando regras de negócio...")
sleep(0.7)
print("Elaborando requisitos de sistema...")
sleep(0.7)
print("Priorizando...")
sleep(0.7)
print("...")
sleep(0.7)

print("Iniciando especificação de requisitos...")
sleep(0.7)
print("Modelando estrutura abstrata do produto...")
sleep(0.7)
print("Gerando relatório de requisitos...")
sleep(0.7)
print("...")
sleep(1)

print("Iniciando validaçao de requisitos...")
sleep(0.7)
print("Apresentando modelo abstrato...")
sleep(0.7)
print("Ajustando estrutura...")
sleep(0.7)
print("Análise do relatório produzido...")
sleep(0.7)
print("Resolvendo conflitos de requisitos...")
sleep(0.7)
print("Ajustando requisitos de usuário...")
sleep(0.7)
print("Apresentando restrições de funcionalidade e produção...")
sleep(0.7)
print("Desambiguando...")
sleep(1)

print("--------------------FIM DO SUB-PROCESSO DE REQUISITOS--------------------")